package ru.rayanis.stroyka.constants

object FirebaseAuthConstants {
    val ERROR_EMAIL_ALREADY_IN_USE = "ERROR_EMAIL_ALREADY_IN_USE"
    val ERROR_INVALID_EMAIL = "ERROR_INVALID_EMAIL"
    val ERROR_WRONG_PASSWORD = "ERROR_WRONG_PASSWORD"
    val ERROR_WEAK_PASSWORD = "ERROR_WEAK_PASSWORD"
    val ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND"
}